import { unlink } from 'node:fs/promises';
import path from 'node:path';

import { Project, IndentationText, QuoteKind, ScriptKind } from 'ts-morph';

import { createRuntimeError } from '../../utils/errors';
import {
  readFileIfExists,
  renderConfigRegistrationLiteral,
  renderLocaleConfigLiteral
} from '../file-conventions/shared';

import type { LocaleConfig } from '../../core/types';
import type { RouteHandlerRoutingStrategy } from '../policy/routing-strategy';
import type { ResolvedRouteHandlersRoutingPolicy } from '../types';
import type { RouteHandlerProxyConfigRegistration } from '../proxy/runtime/types';

const ROOT_INSTRUMENTATION_FILE_PATH = 'instrumentation.ts';
const ROOT_INSTRUMENTATION_JS_FILE_PATH = 'instrumentation.js';
const SRC_INSTRUMENTATION_FILE_PATH = path.join('src', 'instrumentation.ts');
const SRC_INSTRUMENTATION_JS_FILE_PATH = path.join('src', 'instrumentation.js');

/**
 * Ownership marker embedded into plugin-generated root instrumentation files.
 */
export const ROUTE_HANDLER_PROXY_INSTRUMENTATION_OWNERSHIP_MARKER =
  'next-slug-splitter:experimental-proxy-instrumentation';

/**
 * Resolve the plugin-owned generated root instrumentation file path.
 *
 * @param rootDir - Application root directory.
 * @returns Absolute file path for the generated `instrumentation.ts`.
 */
const resolveGeneratedInstrumentationFilePath = (rootDir: string): string =>
  // The generated file deliberately lives at the app root because that is the
  // file-convention location Next scans for instrumentation registration. We
  // keep the synthetic file at the most explicit location so developers can
  // easily observe startup-prewarm ownership during experiments.
  path.join(rootDir, ROOT_INSTRUMENTATION_FILE_PATH);

/**
 * List every instrumentation file convention that would conflict with the
 * plugin-owned startup prewarm bridge.
 *
 * @param rootDir - Application root directory.
 * @returns Absolute file paths that must remain app-owned.
 */
const resolveInstrumentationConflictCandidates = (
  rootDir: string
): Array<string> => [
  path.join(rootDir, ROOT_INSTRUMENTATION_FILE_PATH),
  path.join(rootDir, ROOT_INSTRUMENTATION_JS_FILE_PATH),
  path.join(rootDir, SRC_INSTRUMENTATION_FILE_PATH),
  path.join(rootDir, SRC_INSTRUMENTATION_JS_FILE_PATH)
];

/**
 * Determine whether a file is owned by the plugin-generated instrumentation
 * lifecycle.
 *
 * @param sourceText - Source text to inspect.
 * @returns `true` when the ownership marker is present.
 */
const isPluginOwnedInstrumentationFile = (sourceText: string): boolean =>
  sourceText.includes(ROUTE_HANDLER_PROXY_INSTRUMENTATION_OWNERSHIP_MARKER);

/**
 * Render the plugin-owned root `instrumentation.ts` source.
 *
 * @param input - Source rendering input.
 * @returns Complete TypeScript source text.
 *
 * @remarks
 * The generated file intentionally stays tiny. It owns only:
 * - the root instrumentation file convention that Next scans
 * - one startup `register()` hook
 * - a delegation call back into the library-owned worker-prewarm runtime
 *
 * All actual prewarm semantics still live in the package runtime imported
 * below, so the generated root file is purely a startup bridge between Next's
 * instrumentation convention and our internal worker-prewarm helper.
 */
const renderRouteHandlerInstrumentationSource = ({
  localeConfig,
  configRegistration
}: {
  localeConfig: LocaleConfig;
  configRegistration: RouteHandlerProxyConfigRegistration;
}): string =>
  [
    '/**',
    ` * ${ROUTE_HANDLER_PROXY_INSTRUMENTATION_OWNERSHIP_MARKER}`,
    ' *',
    ' * This file is generated by next-slug-splitter for optional dev-only',
    ' * proxy worker prewarm. It intentionally stays tiny and owns only the',
    ' * root instrumentation convention plus one delegation call back into the',
    ' * library-owned startup prewarm helper.',
    ' */',
    "import { prewarmRouteHandlerProxyWorker } from 'next-slug-splitter/next/instrumentation';",
    '',
    'const LOCALE_CONFIG = ' + renderLocaleConfigLiteral(localeConfig) + ';',
    'const CONFIG_REGISTRATION = ' +
      renderConfigRegistrationLiteral(
        configRegistration.configPath,
        configRegistration.rootDir
      ) +
      ';',
    '',
    'export async function register() {',
    '  await prewarmRouteHandlerProxyWorker({',
    '    localeConfig: {',
    '      locales: [...LOCALE_CONFIG.locales],',
    '      defaultLocale: LOCALE_CONFIG.defaultLocale',
    '    },',
    '    configRegistration: {',
    '      configPath: CONFIG_REGISTRATION.configPath,',
    '      rootDir: CONFIG_REGISTRATION.rootDir',
    '    }',
    '  });',
    '}',
    ''
  ].join('\n');

/**
 * Write the plugin-owned root `instrumentation.ts`.
 *
 * @param input - File write input.
 * @param input.instrumentationFilePath - Absolute output path.
 */
const writeGeneratedInstrumentationFile = async ({
  instrumentationFilePath,
  localeConfig,
  configRegistration
}: {
  instrumentationFilePath: string;
  localeConfig: LocaleConfig;
  configRegistration: RouteHandlerProxyConfigRegistration;
}): Promise<void> => {
  // `ts-morph` is used even though the file is small because it gives us a
  // deterministic save/format pipeline and keeps generated output readable when
  // developers inspect the synthetic root file during the experiment.
  const project = new Project({
    manipulationSettings: {
      indentationText: IndentationText.TwoSpaces,
      quoteKind: QuoteKind.Single
    },
    useInMemoryFileSystem: false
  });
  const sourceFile = project.createSourceFile(
    instrumentationFilePath,
    renderRouteHandlerInstrumentationSource({
      localeConfig,
      configRegistration
    }),
    {
      overwrite: true,
      scriptKind: ScriptKind.TS
    }
  );

  sourceFile.formatText();
  await sourceFile.save();
};

/**
 * Ensure no app-owned instrumentation files would be overwritten.
 *
 * @param rootDir - Application root directory.
 * @param generatedInstrumentationFilePath - Absolute path for the
 * plugin-owned file.
 * @returns A promise that settles after conflict scanning completes.
 */
const assertNoInstrumentationConflicts = async (
  rootDir: string,
  generatedInstrumentationFilePath: string
): Promise<void> => {
  for (const candidateFilePath of resolveInstrumentationConflictCandidates(
    rootDir
  )) {
    const sourceText = await readFileIfExists(candidateFilePath);

    if (sourceText == null) {
      // No file means no ownership decision is needed, so we simply continue
      // scanning the remaining convention locations.
      continue;
    }

    if (
      candidateFilePath === generatedInstrumentationFilePath &&
      isPluginOwnedInstrumentationFile(sourceText)
    ) {
      // A previous plugin-generated file is safe to replace in place. This is
      // the normal in-place update path when worker prewarm stays enabled
      // across runs.
      continue;
    }

    // Any pre-existing app-owned instrumentation file is treated as a hard
    // conflict. The library must never silently override the application's own
    // startup hook.
    throw createRuntimeError(
      'Route-handler proxy instrumentation prewarm cannot run because an existing app-owned instrumentation file is present.',
      {
        filePath: candidateFilePath
      }
    );
  }
};

/**
 * Remove the plugin-owned root `instrumentation.ts` when present.
 *
 * @param rootDir - Application root directory.
 * @returns A promise that settles after any plugin-owned instrumentation file
 * is removed.
 */
const removeGeneratedInstrumentationFileIfPresent = async (
  rootDir: string
): Promise<void> => {
  const instrumentationFilePath =
    resolveGeneratedInstrumentationFilePath(rootDir);
  const sourceText = await readFileIfExists(instrumentationFilePath);

  if (sourceText == null || !isPluginOwnedInstrumentationFile(sourceText)) {
    // Cleanup must never delete user-owned files. The ownership marker is the
    // hard guardrail that keeps this lifecycle safe.
    return;
  }

  // Once ownership is confirmed, deletion is unconditional. We do not keep the
  // stale file around because its mere presence changes how Next boots.
  await unlink(instrumentationFilePath);
};

/**
 * Synchronize the plugin-owned root `instrumentation.ts` file.
 *
 * @param input - Synchronization input.
 * @param input.rootDir - Application root directory.
 * @param input.strategy - Active routing strategy.
 * @param input.routingPolicy - Resolved app-level routing policy.
 * @param input.localeConfig - Shared app locale config.
 * @param input.configRegistration - Adapter-time config registration.
 *
 * @remarks
 * This module owns only filesystem presence:
 * - create the instrumentation file when proxy worker prewarm is active
 * - remove the instrumentation file when startup prewarm is inactive
 *
 * It does not decide how the worker is prewarmed once Next loads the root
 * file. That concern lives in `proxy/runtime/prewarm.ts`, which is entered
 * through the thin `next/instrumentation` bridge exported by the package.
 */
export const synchronizeRouteHandlerInstrumentationFile = async ({
  rootDir,
  strategy,
  routingPolicy,
  localeConfig,
  configRegistration = {}
}: {
  rootDir: string;
  strategy: RouteHandlerRoutingStrategy;
  routingPolicy: ResolvedRouteHandlersRoutingPolicy;
  localeConfig: LocaleConfig;
  configRegistration?: RouteHandlerProxyConfigRegistration;
}): Promise<void> => {
  if (
    strategy.kind !== 'proxy' ||
    routingPolicy.workerPrewarm !== 'instrumentation'
  ) {
    // Any non-proxy or non-prewarm mode must actively clean up a stale
    // plugin-generated instrumentation file so later runs do not continue to
    // execute startup prewarm by accident.
    await removeGeneratedInstrumentationFileIfPresent(rootDir);
    return;
  }

  const generatedInstrumentationFilePath =
    resolveGeneratedInstrumentationFilePath(rootDir);
  await assertNoInstrumentationConflicts(
    rootDir,
    generatedInstrumentationFilePath
  );
  // Locale config and config registration are embedded into the generated
  // startup hook so it can stay self-contained when Next loads it through the
  // instrumentation file convention.
  await writeGeneratedInstrumentationFile({
    instrumentationFilePath: generatedInstrumentationFilePath,
    localeConfig,
    configRegistration
  });
};
