import type { LocaleConfig } from '../../../core/types';
import type {
  BootstrapGenerationToken,
  RouteHandlerProxyConfigRegistration
} from '../runtime/types';

/**
 * Shared input required to create or resolve one persistent worker session.
 *
 * @remarks
 * This shape captures the full parent-side session identity:
 * - `localeConfig` defines the locale semantics the worker must bootstrap with
 * - `bootstrapGenerationToken` ties the session to one parent bootstrap cycle
 * - `configRegistration` scopes the session to one registered app/config root
 */
export type RouteHandlerProxyWorkerSessionInput = {
  /**
   * Locale semantics for the current worker generation.
   */
  localeConfig: LocaleConfig;
  /**
   * Parent-issued bootstrap generation token.
   */
  bootstrapGenerationToken: BootstrapGenerationToken;
  /**
   * Adapter-time config registration forwarded by the generated root proxy.
   */
  configRegistration: RouteHandlerProxyConfigRegistration;
};

/**
 * Serialized request sent from the thin proxy runtime into the dev-only lazy
 * worker session.
 *
 * @remarks
 * Design aspects:
 * - Transport: requests stay JSON-serializable so they can travel over Node
 *   IPC without custom encoding.
 * - Boundary: the thin proxy runtime forwards only the data required to
 *   classify or bootstrap one request.
 * - Isolation: heavy planning state remains worker-local instead of being
 *   reconstructed in the proxy runtime.
 *
 * Request kinds:
 * - `bootstrap`: one-time session initialization for the current parent
 *   bootstrap generation. The worker uses the generation token, locale
 *   semantics, and adapter-owned config registration to load the persisted
 *   structural manifest, reload runtime attachments, validate that both match
 *   the current generation, and keep the derived planner state in memory for
 *   later lazy-miss requests.
 * - `resolve-lazy-miss`: classify one pathname using the in-memory state
 *   prepared by an earlier `bootstrap` request.
 */
type RouteHandlerProxyWorkerRequestBase = {
  /**
   * Stable IPC correlation id generated by the parent runtime.
   */
  requestId: string;
};

export type RouteHandlerProxyWorkerRequest =
  RouteHandlerProxyWorkerRequestBase &
    (
      | {
          kind: 'bootstrap';

          /**
           * Parent-issued generation token expected to match the persisted
           * worker bootstrap manifest on disk.
           */
          bootstrapGenerationToken: BootstrapGenerationToken;

          /**
           * Locale semantics expected to match the current persisted bootstrap
           * manifest before the worker accepts it.
           */
          localeConfig: LocaleConfig;

          /**
           * Clear adapter-owned registration values used to reload runtime
           * attachments inside the worker for this bootstrap generation.
           *
           * The worker still loads runtime attachments itself; this request
           * only carries the root/config identity needed to do that reload.
           */
          configRegistration: RouteHandlerProxyConfigRegistration;
        }
      | {
          kind: 'resolve-lazy-miss';

          /**
           * Public request pathname to classify against the bootstrapped
           * targets.
           */
          pathname: string;
        }
    );

/**
 * Acknowledgement returned when the long-lived worker session has finished its
 * one-time bootstrap work for the current generation.
 */
export type RouteHandlerProxyWorkerBootstrapResponse = {
  kind: 'bootstrapped';
  bootstrapGenerationToken: BootstrapGenerationToken;
};

/**
 * Serialized worker response for one proxy lazy-miss resolution.
 *
 * @remarks
 * Design aspects:
 * - Scope: the proxy runtime only receives the semantic routing outcome.
 * - Stability: internal analysis objects stay inside the worker and do not
 *   become part of the wire contract.
 * - Evolution: keeping the response small reduces coupling between the thin
 *   runtime and the worker implementation.
 */
export type RouteHandlerProxyWorkerResponse =
  | {
      kind: 'heavy';
      source: 'discovery' | 'fresh' | 'cache';
      rewriteDestination: string;
      routeBasePath: string;
    }
  | {
      kind: 'pass-through';
      reason:
        | 'no-target'
        | 'missing-route-file'
        | 'light'
        | 'missing-rewrite-destination';
    };

/**
 * One IPC response envelope traveling from the worker back to the thin proxy
 * runtime.
 *
 * @remarks
 * Design aspects:
 * - Multiplexing: request ids let one long-lived worker serve multiple
 *   overlapping requests.
 * - Symmetry: both bootstrap and lazy-miss responses use the same outer
 *   envelope shape.
 * - Failure reporting: worker-side errors stay request-scoped instead of
 *   collapsing the entire session immediately.
 */
export type RouteHandlerProxyWorkerResponseEnvelope =
  | {
      requestId: string;
      ok: true;
      response:
        | RouteHandlerProxyWorkerBootstrapResponse
        | RouteHandlerProxyWorkerResponse;
    }
  | {
      requestId: string;
      ok: false;
      error: {
        message: string;
      };
    };
