import { statSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';

import { MODULE_SOURCE_EXTENSIONS } from './extensions';
import type { ModuleReference, ResolvedModuleReference } from './types';

/**
 * Virtual file path used only to anchor Node package resolution at the app
 * root.
 *
 * Key aspects:
 * 1. `createRequire(...)` expects an absolute file path.
 * 2. The anchor path does not need to exist on disk.
 * 3. A synthetic file under `rootDir` makes package resolution start from the
 *    application root.
 * 4. This avoids requiring the application to provide `package.json` as the
 *    resolution anchor.
 */
const APP_ROOT_PACKAGE_RESOLUTION_ANCHOR = '__app_root_resolver__';

/**
 * Determine whether a local module path already ends with a known source-file
 * extension.
 *
 * Key aspects:
 * 1. `path.extname(...)` is not used here.
 * 2. Next.js dynamic route filenames such as `[...slug]` and `[[...slug]]`
 *    contain dots as part of the route syntax.
 * 3. `path.extname('[...slug]')` incorrectly reports `.slug]`.
 * 4. That result makes catch-all route modules look like already-extended
 *    files and skips `.[tj]sx` candidate probing.
 */
const hasKnownSourceExtension = (modulePath: string): boolean => {
  for (const extension of MODULE_SOURCE_EXTENSIONS) {
    if (modulePath.endsWith(extension)) {
      return true;
    }
  }
  return false;
};

/**
 * Safely determines whether an absolute path points to an existing file.
 *
 * Validation checks:
 * 1. The filesystem is queried synchronously using `statSync`.
 * 2. If the path resolves to a valid, regular file, `true` is returned.
 * 3. Any filesystem error (such as `ENOENT` or a permission error) is caught safely without throwing.
 *
 * @example
 * ```ts
 * isExistingFile('/app/tsconfig.json')
 * // => true
 * 
 * isExistingFile('/app/missing.ts')
 * // => false
 * ```
 *
 * @param filePath - The absolute filesystem path to check.
 * @returns `true` if the path exists on disk and is a regular file; otherwise `false`.
 */
const isExistingFile = (filePath: string): boolean => {
  try {
    return statSync(filePath).isFile();
  } catch {
    return false;
  }
};

/**
 * Verifies that an absolute file path exists on disk.
 *
 * Validation checks:
 * 1. The filesystem is queried synchronously using `statSync`.
 * 2. The target must be an existing, regular file.
 * 3. An error is thrown if the file cannot be accessed or is a directory.
 *
 * @example
 * ```ts
 * resolveExactExistingFilePath('/app/tsconfig.json')
 * // => '/app/tsconfig.json'
 * ```
 *
 * @param absolutePath - The absolute filesystem path to verify.
 * @returns The original absolute path if a valid file exists.
 * @throws An error when the file does not exist or cannot be accessed.
 */
const resolveExactExistingFilePath = (absolutePath: string): string => {
  if (isExistingFile(absolutePath)) {
    return absolutePath;
  }

  throw new Error(`Could not resolve local file path "${absolutePath}".`);
};

/**
 * Resolves a local module path by probing known source extensions.
 *
 * Resolution steps:
 * 1. If the path already has a known extension, it is checked exactly as provided.
 * 2. If it is extensionless, candidate paths are generated by appending recognized extensions.
 * 3. Directory index candidates are generated by appending `/index` and known extensions.
 * 4. All candidates are checked synchronously; the first existing file is returned.
 *
 * @example
 * ```ts
 * resolveExistingLocalModulePath('/app/src/utils')
 * // => '/app/src/utils.ts'
 * 
 * resolveExistingLocalModulePath('/app/src/components')
 * // => '/app/src/components/index.tsx'
 * ```
 *
 * @param absolutePath - The base absolute module path to resolve.
 * @returns The fully resolved absolute file path of the existing module.
 * @throws An error when no candidate matches an existing file.
 */
const resolveExistingLocalModulePath = (absolutePath: string): string => {
  const extensionsArray = Array.from(MODULE_SOURCE_EXTENSIONS);
  const candidates =
    hasKnownSourceExtension(absolutePath)
      ? [absolutePath]
      : [
        absolutePath,
        ...extensionsArray.map(extension => `${absolutePath}${extension}`),
        ...extensionsArray.map(extension =>
          path.join(absolutePath, `index${extension}`)
        )
      ];

  for (const candidate of candidates) {
    if (isExistingFile(candidate)) {
      return candidate;
    }
  }

  throw new Error(`Could not resolve local module path "${absolutePath}".`);
};

/**
 * Shared logic for resolving a module reference to an absolute path.
 *
 * Resolution steps:
 * 1. Package References: Resolved via Node's `createRequire` anchored at the application root.
 *    This returns the actual imported file path from within `node_modules` or packages.
 * 2. Absolute/Relative Files: Standardized to a guaranteed absolute path via `rootDir`.
 * 3. Finalization: For non-package files, the structured absolute path is passed to 
 *    `resolveLocalPath` to execute final behaviors (e.g., probing extensions vs exact match).
 *
 * @param rootDir - Application root directory used to anchor resolution.
 * @param reference - The module reference object to be resolved.
 * @param resolveLocalPath - Callback to perform final filesystem checks or transformations on the absolute local path.
 * @returns The final absolute file path resolved by the callback, or the native package module path.
 */
const applyModuleReferenceResolution = (
  rootDir: string,
  reference: ModuleReference | ResolvedModuleReference,
  resolveLocalPath: (absolutePath: string) => string
): string => {
  if (reference.kind === 'package') {
    /**
     * 1. Node package resolution requires an absolute anchor path.
     * 2. A synthetic file path under `rootDir` provides this anchor.
     * 3. Subpath and workspace resolutions evaluate correctly from the project root.
     * 4. An actual `package.json` file is not required on disk at the anchor path.
     */
    const requireFromRoot = createRequire(
      path.resolve(rootDir, APP_ROOT_PACKAGE_RESOLUTION_ANCHOR)
    );
    return requireFromRoot.resolve(reference.specifier);
  }

  const absolutePath =
    reference.kind === 'absolute-file'
      ? path.resolve(reference.path)
      : path.resolve(rootDir, reference.path);

  return resolveLocalPath(absolutePath);
};

/**
 * Resolve one module reference to an existing absolute module path.
 * 
 * Local files are probed with known source extensions.
 *
 * @example
 * ```ts
 * resolveModuleReferenceToPath('/app', { kind: 'relative-file', path: 'src/config' })
 * // => '/app/src/config.ts'
 * 
 * resolveModuleReferenceToPath('/app', { kind: 'absolute-file', path: '/app/src/config' })
 * // => '/app/src/config.ts'
 * 
 * resolveModuleReferenceToPath('/app', { kind: 'package', specifier: 'react' })
 * // => '/app/node_modules/react/index.js'
 * ```
 *
 * @param rootDir - Application root directory used to resolve relative paths or anchor package resolutions.
 * @param reference - The module reference to resolve.
 * @returns Absolute module file path.
 * @throws When the reference cannot be resolved to an existing module.
 */
export const resolveModuleReferenceToPath = (
  rootDir: string,
  reference: ModuleReference | ResolvedModuleReference
): string => applyModuleReferenceResolution(rootDir, reference, resolveExistingLocalModulePath);

/**
 * Resolve one module reference to an existing absolute file path without
 * probing source-file extensions.
 * 
 * Matches the file exactly as referenced.
 *
 * @example
 * ```ts
 * resolveModuleReferenceToFilePath('/app', { kind: 'relative-file', path: 'tsconfig.json' })
 * // => '/app/tsconfig.json'
 * 
 * resolveModuleReferenceToFilePath('/app', { kind: 'absolute-file', path: '/app/tsconfig.json' })
 * // => '/app/tsconfig.json'
 * 
 * resolveModuleReferenceToFilePath('/app', { kind: 'package', specifier: 'react/package.json' })
 * // => '/app/node_modules/react/package.json'
 * ```
 *
 * @param rootDir - Application root directory used to resolve relative paths or anchor package resolutions.
 * @param reference - The module reference to resolve.
 * @returns Absolute existing file path.
 * @throws When the reference does not resolve to an existing file.
 */
export const resolveModuleReferenceToFilePath = (
  rootDir: string,
  reference: ModuleReference | ResolvedModuleReference
): string => applyModuleReferenceResolution(rootDir, reference, resolveExactExistingFilePath);
